### PR TITLE
Add amazon link

### PR DESCRIPTION
**Pull request by spencercanner**
Desktop:
image
image

Mobile:
image
image

### CODE REVIEW

**Comment by oghosa** [comment]
@spencercanner Tracking has now been added for Amazon links. I also Included a value of 1 to the event just to see view data assuming we received $1 per click on Amazon. You may preview the google tracking changes here: https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-MLKC2R9&gtm_auth=Wyl9WxGWhR_UyG-wNA1WFg&gtm_preview=env-5&gtm_debug=x

**Comment by spencercanner** [comment]
@oghosa even with the buy now centered, something still looks off 
image
We could do something like this, which optimizes the space around each item: 
image

For 3. I have it set up so that longer titles will push the dark grey area down but I think this still needs some work. 
image
I still agree with increasing the height of the dark grey though since there's almost always blank space at the bottom of the overlay now

**Comment by spencercanner** [comment]
The height is still the same, I think it might have just been some of the books I chose

**Comment by oghosa** [comment]
@spencercanner looks good to me. let's ship it! 
screen shot 2018-10-16 at 11 26 59 pm
screen shot 2018-10-16 at 11 27 05 pm
screen shot 2018-10-16 at 11 27 14 pm
screen shot 2018-10-16 at 11 27 23 pm
screen shot 2018-10-16 at 11 27 45 pm
screen shot 2018-10-16 at 11 27 53 pm

**Pull request merged**
